### ISSUE TITLE
fugue metadata upgrades

### ISSUE THREAD

**Issue by evanwill** [uidaholib/documents-digital-collections-template#5]
In the new [Fugue digital archive](https://www.lib.uidaho.edu/digital/fugue/), older items have metadata of contributors and editors. More recent items 2017+ have no metadata (except date and issue_number). Upgrading the metadata for the newer items would be a good short-ish metadata project (about 18 items).

- [x] extract list of editors to `editors` column
- [x] extract list of contributors to `creator` column
- [x] check `title` (I just generated these from the number and date)

**Comment by evanwill** [comment]
@mkoepele this would be a good project for you, and get to read UofI poetry!

**Comment by mkoepele** [comment]
Added metadata to the more recent items!
